services:
  db:
    image: postgres:17.1-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  django:
    build: .
    container_name: django-docker
    ports:
      -  "8000:8000"
    depends_on:
      - db
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
volumes:
    postgres_data: