services:
  db:
    container_name: db
    image: postgres:15
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stud_admin"]
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env


  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      OLLAMA_HOST: 0.0.0.0:11434
    dns:
      - 1.1.1.1
      - 8.8.8.8
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      interval: 5s
      timeout: 5s
      retries: 20


  ollama-pull:
    image: ollama/ollama:latest
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      OLLAMA_HOST: http://ollama:11434
    volumes:
      - ollama_data:/root/.ollama
    dns:
      - 1.1.1.1
      - 8.8.8.8
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "ollama pull nomic-embed-text &&
       ollama list"

  django:
    build: .
    container_name: django-docker
    ports:
      -  "8000:8000"
    volumes:
      - .:/app
    depends_on:
      ollama:
        condition: service_healthy
      ollama-pull:
        condition: service_completed_successfully
    environment:
      OLLAMA_HOST: http://ollama:11434
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
volumes:
    postgres_data:
    ollama_data: